.PHONY: all
all:
	#@clear
	ls 
	@echo
	pwd
	git config user.name "deyisafe"
	git config user.email "abc123@deyisafe.com"		
	@echo
	git add -A .
	@echo
	git commit -a -m "www.deyisafe.com"
	@echo	
	git push
	@echo 